# docker-compose.yml
version: '3.8'

services:
  document:
    build: .
    container_name: document
    restart: unless-stopped
    ports:
      - "3007:3007"
    env_file:
      - .env
    networks:
      - ngx-net

networks:
  ngx-net:
    external: true