/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/navigation/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NavigationController_sections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/section/create-section": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_createSection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/section/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NavigationController_section"];
        put?: never;
        post?: never;
        delete: operations["NavigationController_deleteSection"];
        options?: never;
        head?: never;
        patch: operations["NavigationController_updateSection"];
        trace?: never;
    };
    "/navigation/workshops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NavigationController_workshops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/workshop/create-workshop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_createWorkshop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/workshop/edit-workshop-name-and-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_editWorkshopNameAndSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/workshop/delete-workshop-and-workshop-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_deleteWorkshopAndWorkshops"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/workshop/sort-workshops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_sortWorkshops"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/page/create-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_createPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/page/add-reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_addReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/page/delete-page-and-update-workshop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_deletePageAndUpdateWorkshop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/page/edit-page-name-update-workshop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_editPageNameUpdateWorkshop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navigation/page/sort-pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NavigationController_sortPages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workshop/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkshopController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workshop/workshops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkshopController_workshops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workshop/{objectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkshopController_workshop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workshop/update-workshop-html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkshopController_updateWorkshopHtml"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SectionDto: {
            _id: string;
            sectionTitle: string;
            /** @default  */
            sectionDescription: string;
            summary: number;
            menuSvgPath: string;
            headerSvgPath: string;
            categoriesLastUpdated: string;
        };
        WorkshopPageIdentifierDto: {
            /** @description Workshop entry ID; for PAGE entries this is the document page ID. */
            _id: string;
            /** @description Workshop navigation label. */
            name: string;
            /** @description Position of the entry in the workshop journey */
            sortId: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PAGE";
        };
        AssessmentTestIdentifierDto: {
            /** @description Workshop entry ID; for PAGE entries this is the document page ID. */
            _id: string;
            /** @description Workshop navigation label. */
            name: string;
            /** @description Position of the entry in the workshop journey */
            sortId: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ASSESSMENT_TEST";
            /** @description Opaque assessment-test ID supplied by the frontend */
            resourceId: string;
        };
        CodingLabIdentifierDto: {
            /** @description Workshop entry ID; for PAGE entries this is the document page ID. */
            _id: string;
            /** @description Workshop navigation label. */
            name: string;
            /** @description Position of the entry in the workshop journey */
            sortId: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "CODING_LAB";
            /** @description Opaque coding-lab ID supplied by the frontend */
            resourceId: string;
        };
        SectionsMapDto: {
            sections: {
                [key: string]: components["schemas"]["SectionDto"];
            };
        };
        CreateSectionDto: {
            /** @description Display name of the section */
            sectionTitle: string;
            /** @description Description of the section; an empty string clears it */
            sectionDescription?: string;
        };
        UpdateSectionDto: {
            /** @description Display name of the section */
            sectionTitle?: string;
            /** @description Description of the section; an empty string clears it */
            sectionDescription?: string;
            summary?: number;
            menuSvgPath?: string;
            headerSvgPath?: string;
        };
        DeleteResultDto: {
            acknowledged: boolean;
            deletedCount: number;
        };
        WorkshopDto: {
            _id: string;
            workshopDocumentGroupId: string;
            sectionId: string;
            /** @default 0 */
            sortId: number;
            name: string;
            summary: string;
            /** @default https://via.placeholder.com/250/400 */
            thumbnail: string;
            workshopDocuments: (components["schemas"]["WorkshopPageIdentifierDto"] | components["schemas"]["AssessmentTestIdentifierDto"] | components["schemas"]["CodingLabIdentifierDto"])[];
            /** Format: date-time */
            workshopDocumentsLastUpdated: string;
        };
        CreateWorkshopDto: {
            _id: string;
            sectionId: string;
            workshopDocumentGroupId?: string;
            /** @default 0 */
            sortId: number;
            name: string;
            summary: string;
            /** @default https://via.placeholder.com/250/400 */
            thumbnail: string;
            /** Format: date-time */
            workshopDocumentsLastUpdated?: string;
        };
        UpdateWorkshopDto: {
            _id?: string;
            sectionId?: string;
            workshopDocumentGroupId?: string;
            /** @default 0 */
            sortId: number;
            name?: string;
            summary?: string;
            /** @default https://via.placeholder.com/250/400 */
            thumbnail: string;
            /** Format: date-time */
            workshopDocumentsLastUpdated?: string;
        };
        CreateWorkshopPageDto: {
            workshopId: string;
            /** @default Page */
            name: string;
            /** @default 0 */
            sortId: number;
            /** @default PAGE */
            pageType: string;
            /** Format: date-time */
            lastUpdated?: string;
            /** @description Serialized JSON of the document blocks */
            html?: string;
        };
        AddWorkshopReferenceDto: {
            workshopId: string;
            /** @enum {string} */
            kind: "ASSESSMENT_TEST" | "CODING_LAB";
            /** @description Opaque resource ID; no remote existence check is performed */
            resourceId: string;
            name: string;
        };
        DeletePageParamsDto: {
            _id: string;
            workshopId: string;
            name: string;
        };
        EditPageNameUpdateWorkshopDto: {
            _id: string;
            name: string;
            workshopId: string;
        };
        WorkshopPageDto: {
            _id: string;
            workshopGroupId: string;
            /** @default Page */
            name: string;
            /** @default 0 */
            sortId: number;
            /** @default PAGE */
            pageType: string;
            /** Format: date-time */
            lastUpdated: string;
            /** @description Serialized JSON of the document blocks */
            html: string;
            __v: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    NavigationController_sections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionsMapDto"];
                };
            };
        };
    };
    NavigationController_createSection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSectionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionDto"];
                };
            };
        };
    };
    NavigationController_section: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Section key: a Mongo ObjectId string or a legacy string key */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionDto"];
                };
            };
            /** @description Invalid section key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Section not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NavigationController_deleteSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Section key: a Mongo ObjectId string or a legacy string key */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResultDto"];
                };
            };
            /** @description Invalid section key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Section not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Section contains workshops */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NavigationController_updateSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Section key: a Mongo ObjectId string or a legacy string key */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSectionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionDto"];
                };
            };
            /** @description Invalid section key or update */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Section not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NavigationController_workshops: {
        parameters: {
            query: {
                section: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDto"][];
                };
            };
        };
    };
    NavigationController_createWorkshop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkshopDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDto"];
                };
            };
        };
    };
    NavigationController_editWorkshopNameAndSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkshopDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDto"];
                };
            };
        };
    };
    NavigationController_deleteWorkshopAndWorkshops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResultDto"];
                };
            };
        };
    };
    NavigationController_sortWorkshops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDto"][];
                };
            };
        };
    };
    NavigationController_createPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkshopPageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDto"];
                };
            };
        };
    };
    NavigationController_addReference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWorkshopReferenceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDto"];
                };
            };
            /** @description Invalid reference */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workshop not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NavigationController_deletePageAndUpdateWorkshop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletePageParamsDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResultDto"];
                };
            };
        };
    };
    NavigationController_editPageNameUpdateWorkshop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditPageNameUpdateWorkshopDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDto"];
                };
            };
        };
    };
    NavigationController_sortPages: {
        parameters: {
            query: {
                workshopId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": (components["schemas"]["WorkshopPageIdentifierDto"] | components["schemas"]["AssessmentTestIdentifierDto"] | components["schemas"]["CodingLabIdentifierDto"])[];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopDto"];
                };
            };
            /** @description Invalid journey permutation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workshop not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Journey changed during reorder */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkshopController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkshopController_workshops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopPageDto"][];
                };
            };
        };
    };
    WorkshopController_workshop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopPageDto"];
                };
            };
        };
    };
    WorkshopController_updateWorkshopHtml: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopPageDto"];
                };
            };
        };
    };
}
