/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/navigation/sections': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['NavigationController_sections'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/workshops': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['NavigationController_workshops'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/workshop/create-workshop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NavigationController_createWorkshop'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/workshop/edit-workshop-name-and-summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NavigationController_editWorkshopNameAndSummary'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/workshop/delete-workshop-and-workshop-documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NavigationController_deleteWorkshopAndWorkshops'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/workshop/sort-workshops': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NavigationController_sortWorkshops'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/page/create-page': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NavigationController_createPage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/page/delete-page-and-update-workshop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NavigationController_deletePageAndUpdateWorkshop'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/page/edit-page-name-update-workshop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NavigationController_editPageNameUpdateWorkshop'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/navigation/page/sort-pages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['NavigationController_sortPages'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workshop/workshops': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['WorkshopController_workshops'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workshop/{objectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['WorkshopController_workshop'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workshop/update-workshop-html': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['WorkshopController_updateWorkshopHtml'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SectionDto: {
      _id: string;
      sectionTitle: string;
      summary: number;
      menuSvgPath: string;
      headerSvgPath: string;
      categoriesLastUpdated: string;
    };
    SectionsMapDto: {
      sections: {
        [key: string]: components['schemas']['SectionDto'];
      };
    };
    Workshop: Record<string, never>;
    WorkshopDocumentIdentifierDto: {
      /** @description Object id of the workshop-document. */
      _id: string;
      /** @description Display name of the workshop-document. */
      name: string;
      /** @description Position of the doc item in the section's list */
      sortId: number;
    };
    CreateWorkshopDto: {
      _id: string;
      sectionId: string;
      workshopDocumentGroupId?: string;
      /** @default 0 */
      sortId: number;
      name: string;
      summary: string;
      /** @default https://via.placeholder.com/250/400 */
      thumbnail: string;
      workshopDocuments?: components['schemas']['WorkshopDocumentIdentifierDto'][];
      /** Format: date-time */
      workshopDocumentsLastUpdated?: string;
    };
    UpdateWorkshopDto: {
      _id?: string;
      sectionId?: string;
      workshopDocumentGroupId?: string;
      /** @default 0 */
      sortId: number;
      name?: string;
      summary?: string;
      /** @default https://via.placeholder.com/250/400 */
      thumbnail: string;
      workshopDocuments?: components['schemas']['WorkshopDocumentIdentifierDto'][];
      /** Format: date-time */
      workshopDocumentsLastUpdated?: string;
    };
    DeleteResultDto: {
      acknowledged: boolean;
      deletedCount: number;
    };
    WorkshopDocumentDto: {
      _id: string;
      workshopGroupId: string;
      /** @default Page */
      name: string;
      /** @default 0 */
      sortId: number;
      /** @default PAGE */
      pageType: string;
      /** Format: date-time */
      lastUpdated: string;
      /** @description Serialized JSON of the document blocks */
      html: string;
      __v: number;
    };
    PageParamsDto: {
      page: components['schemas']['WorkshopDocumentDto'];
      workshopId: string;
    };
    WorkshopDto: {
      _id: string;
      workshopDocumentGroupId: string;
      sectionId: string;
      /** @default 0 */
      sortId: number;
      name: string;
      summary: string;
      /** @default https://via.placeholder.com/250/400 */
      thumbnail: string;
      workshopDocuments: components['schemas']['WorkshopDocumentIdentifierDto'][];
      /** Format: date-time */
      workshopDocumentsLastUpdated: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  NavigationController_sections: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SectionsMapDto'][];
        };
      };
    };
  };
  NavigationController_workshops: {
    parameters: {
      query: {
        section: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workshop'][];
        };
      };
    };
  };
  NavigationController_createWorkshop: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWorkshopDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workshop'];
        };
      };
    };
  };
  NavigationController_editWorkshopNameAndSummary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateWorkshopDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workshop'];
        };
      };
    };
  };
  NavigationController_deleteWorkshopAndWorkshops: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteResultDto'];
        };
      };
    };
  };
  NavigationController_sortWorkshops: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': string[];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workshop'][];
        };
      };
    };
  };
  NavigationController_createPage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PageParamsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workshop'];
        };
      };
    };
  };
  NavigationController_deletePageAndUpdateWorkshop: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PageParamsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteResultDto'];
        };
      };
    };
  };
  NavigationController_editPageNameUpdateWorkshop: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkshopDocumentDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkshopDto'];
        };
      };
    };
  };
  NavigationController_sortPages: {
    parameters: {
      query: {
        workshopId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': string[];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkshopDto'];
        };
      };
    };
  };
  WorkshopController_workshops: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkshopDocumentDto'][];
        };
      };
    };
  };
  WorkshopController_workshop: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkshopDocumentDto'];
        };
      };
    };
  };
  WorkshopController_updateWorkshopHtml: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkshopDocumentDto'];
        };
      };
    };
  };
}
